---

- hosts: all
  gather_facts: no
  connection: local
  tags:
    - always

  tasks:

  - name: Create working directory
    file:
      dest: "{{ workdir }}"
      mode: 0700
      state: directory
    run_once: True

  - name: Convert distrib to lower case
    set_fact:
      distrib: "{{ distrib|lower }}"

  - name: Set dist_name and dist_release for ubuntu family
    set_fact:
      dist_name: "{{ distrib[:6] }}"
      dist_release: "{{ distrib[6:] }}"
    when: "'ubuntu' in distrib"

  - name: Set os_vendor and os_version for ubuntu family
    set_fact:
      os_vendor: "Canonical Ltd"
      os_version: "{{ dist_release }}.04"
    when: "'ubuntu' in distrib"

  - name: Set dist_name and dist_release for centos family
    set_fact:
      dist_name: "{{ distrib[:6] }}"
      dist_release: "{{ distrib[6] }}"
    when: "'centos' in distrib"

  - name: Set os_vendor and os_version for centos family
    set_fact:
      os_vendor: "CentOS"
      os_version: "{{ dist_release }}.0"
    when: "'centos' in distrib"

  - name: Set dist_name and dist_release for debian family
    set_fact:
      dist_name: "{{ distrib[:6] }}"
      dist_release: "{{ distrib[6:] }}"
    when: "'debian' in distrib"

  - name: Set os_vendor and os_version for debian family
    set_fact:
      os_vendor: "Debian Project"
      os_version: "{{ dist_release }}"
    when: "'debian' in distrib"

# no release, use always last version
  - name: Set dist_name and dist_release for cirros family
    set_fact:
      dist_name: "{{ distrib }}"
      dist_release: ""
    when: "'cirros' in distrib"

  - name: Set os_vendor and os_version for cirros family
    set_fact:
      os_vendor: "CirrOS"
      os_version: "{{ dist_release }}"
    when: "'cirros' in distrib"

  - name: Set hypervisor to localhost when undefined
    set_fact:
      hypervisor: "localhost"
    when: (hypervisor is not defined) or (hypervisor == '')

# local: virsh --connect qemu:///system list
# remote: virsh --connect qemu+ssh://user@host/system list
  - name: Set default libvirt uri
    set_fact:
      libvirt_uri: "qemu:///system"
      libvirt_remote: False

  - name: Set libvirt uri
    set_fact:
      libvirt_uri: "qemu+ssh://{{ hypervisor_user }}@{{ hypervisor }}/system"
      libvirt_remote: True
    when:
      - "hypervisor not in [ '127.0.0.1', 'localhost', inventory_hostname ]"

  - name: group by OS
    group_by: key={{ dist_name }}{{ dist_release }}
    changed_when: False

  - name: Get latest metadata version for cirros
    get_url:
      url: "{{ image.url_base + '/' + image.file_version }}"
      dest: "{{ workdir + '/' + dist_name + '-cirros_version' }}"
      force: yes
    when: "'cirros' in distrib"

  - name: Set dist_release fact for cirros
    set_fact:
#      dist_release: "{{ lookup('file', workdir + '/' + dist_name + '-cirros_version') }}"
      dist_release: "0.3.5"
    when: "'cirros' in distrib"

  - name: Set facts from OS group
    set_fact:
      url_base: "{{ image.url_base }}"
      file_base: "{{ image.file_base }}"
      file_version: "{{ image.file_version | d() }}"
      checksum_file: "{{ image.checksum_file }}"
      signature_file: "{{ image.signature_file | d() }}"
      gpg_key_id: "{{ image.gpg_key_id | d() | replace(' ','') }}"
      gpg_file: "{{ image.gpg_file | d() }}"
      key_server: "{{ image.key_server | d() }}"
      kernel_args: "{{ image.kernel_args }}"

  - name: Adjust file_base fact for group ubuntu18
    set_fact:
      file_base: "ubuntu-{{ dist_release }}.04-server-cloudimg-amd64.img"
    when: distrib == 'ubuntu18'

  - name: Adjust vars for group centos8
    set_fact:
      url_base: "https://cloud.centos.org/centos/{{ dist_release }}/x86_64/images"
      gpg_file: "http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official"
      checksum_file: "CHECKSUM"
      signature_file: "CHECKSUM.asc"
    when: distrib == 'centos8'

  - name: Set fact update_image to default value
    set_fact:
      update_image: False

- hosts: ubuntu14
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: ubuntu16
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: ubuntu18
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: centos7
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: centos8
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: debian8
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: debian9
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: cirros
  gather_facts: no
  connection: local
  run_once: True
  tags:
    - setup

  tasks:

  - name: Include role setup
    include_role:
      name: setup

- hosts: all
  gather_facts: no
  connection: local
  tags:
    - bootstrap

  tasks:

  - name: Include role bootstrap
    include_role:
      name: bootstrap
    when: update_facts is not defined

  - name: Remove working directory
    file:
      dest: "{{ workdir }}"
      state: absent
    when: debug is not defined
    run_once: True
    tags:
      - always
